const locationData = {
  "astrologer-in-ahmedabad.html": {
    city: "Ahmedabad",
    image: "service-session.jpg",
    intro: "Sometimes life brings moments where the next step feels uncertain. Whether the question concerns career, relationships, wellbeing, finances, or a major transition, Vedic Astrology can illuminate the patterns behind the moment."
  },
  "astrologer-in-surat.html": {
    city: "Surat",
    image: "service-office.jpg",
    intro: "The answers you seek may already be present in your birth chart. Dr. Sunnita Bhatt combines deep-rooted Vedic wisdom with a compassionate, modern approach to help clients in Surat find clarity, peace, and meaningful direction."
  }
};

const getLocationKey = () => {
  const slug = location.pathname.split("/").filter(Boolean).pop() || "astrologer-in-surat";
  return slug.endsWith(".html") ? slug : `${slug}.html`;
};
const loc = locationData[getLocationKey()];

if (loc) {
  document.title = `Best Astrologer in ${loc.city} | Riddhi Astrology`;
  document.querySelector("#location-page").innerHTML = `
<section class="service-hero-detail"><div class="service-hero-copy reveal"><p class="eyebrow"><span></span>In-person & online guidance</p><h1>Astrologer in ${loc.city}</h1><p>Personal cosmic guidance for clarity, confidence, and direction.</p><a class="button button-dark" href="contact.html">Book your consultation <span>&nearr;</span></a></div><div class="service-hero-photo reveal"><img src="assets/images/${loc.image}" alt="Dr. Sunnita Bhatt, astrologer serving ${loc.city}"></div></section>
<section class="content-intro section-pad"><div class="reveal"><p class="eyebrow"><span></span>Guidance in ${loc.city}</p><h2>A personal consultation shaped around the questions that matter now.</h2></div><div class="rich-copy reveal"><p>${loc.intro}</p><p>With 31+ years of practice, Dr. Sunnita has guided individuals across India and worldwide through personal, chart-based consultations. Sessions are available online, making the same depth of guidance accessible from ${loc.city} without the need to travel.</p><p>Every reading begins with accurate birth details and a careful understanding of your present situation. The chart is then studied as a complete system, connecting planetary periods, strengths, repeated themes, and the timing surrounding important choices.</p><p>The purpose is to leave you better informed and more grounded. Guidance is explained clearly, with practical context and without fear-based statements or rigid instructions.</p></div></section>
<section class="service-story section-pad"><div class="service-story-copy reveal"><p class="eyebrow light"><span></span>Meet Dr. Sunnita Bhatt</p><p>Known for reading beyond the chart, Dr. Sunnita brings precision, practical insight, and a deeply human conversation to every consultation.</p><p>Her work is grounded in Vedic Astrology, Medical Astrology, and more than three decades of close observation and client guidance.</p><a class="button button-light" href="about.html">Discover her approach <span>&nearr;</span></a></div><div class="service-covers reveal"><p class="eyebrow light"><span></span>Why clients choose Riddhi Astrology</p><div><span>01</span><strong>31+ years of experience</strong></div><div><span>02</span><strong>Personalized chart-based guidance</strong></div><div><span>03</span><strong>Practical, meaningful direction</strong></div><div><span>04</span><strong>Compassionate one-to-one approach</strong></div><div><span>05</span><strong>Online consultations worldwide</strong></div></div></section>
<section class="section-pad"><div class="section-heading reveal"><p class="eyebrow"><span></span>Complete consultations</p><h2>Astrology services<br><em>available in ${loc.city}.</em></h2></div><div class="location-services"><article class="detail-card reveal"><span>01</span><h3>Birth Chart Analysis</h3><p>Understand your personality, strengths, karmic influences, and important planetary periods.</p></article><article class="detail-card reveal"><span>02</span><h3>Marriage & Relationships</h3><p>Explore compatibility, emotional connection, marriage timing, and family harmony.</p></article><article class="detail-card reveal"><span>03</span><h3>Career, Business & Finance</h3><p>Clarify natural talents, professional direction, business potential, and favorable timing.</p></article><article class="detail-card reveal"><span>04</span><h3>Medical Astrology</h3><p>Gain preventive awareness of the energetic relationship between planets, body, and mind.</p></article><article class="detail-card reveal"><span>05</span><h3>Vedic Vastu</h3><p>Bring homes, offices, and commercial spaces into greater balance and flow.</p></article><article class="detail-card reveal"><span>06</span><h3>Numerology</h3><p>Decode your name and birth date for another perspective on life patterns and decisions.</p></article></div></section>
<section class="service-longform section-pad"><div class="service-longform-heading reveal"><p class="eyebrow"><span></span>Online consultation from ${loc.city}</p><h2>The same personal preparation, wherever you are.</h2></div><div class="service-longform-copy reveal"><p>Online consultations make it possible to receive a detailed reading without travelling to the Vadodara or Bharuch offices. Your birth information and questions are shared in advance so the relevant chart patterns can be prepared carefully.</p><p>During the session, Dr. Sunnita explains the reading one-to-one and gives you space to discuss the questions behind your enquiry. Complex astrological observations are translated into clear language and connected to everyday life.</p><p>Clients commonly seek guidance during career changes, relationship decisions, family concerns, business planning, financial transitions, and periods of uncertainty or personal growth.</p><p>Whether the session takes place in person or online, the approach remains private, compassionate, detailed, and focused on practical understanding.</p></div></section>
<section class="service-final"><div><p class="eyebrow light"><span></span>Online from ${loc.city}</p><h2>Find clarity with guidance<br><em>rooted in your chart.</em></h2></div><a class="button button-light" href="contact.html">Book your consultation <span>&nearr;</span></a></section>`;
}
