const menuButton=document.querySelector(".menu-toggle");const mobileMenu=document.querySelector(".mobile-menu");
menuButton?.addEventListener("click",()=>{const open=menuButton.classList.toggle("open");mobileMenu.classList.toggle("open",open);menuButton.setAttribute("aria-expanded",String(open));document.body.style.overflow=open?"hidden":""});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const testimonialSlider=document.querySelector("[data-testimonials]");
if(testimonialSlider){const track=testimonialSlider.querySelector(".testimonial-track");const cards=[...testimonialSlider.querySelectorAll(".testimonial-card")];const sliderCount=testimonialSlider.querySelector("[data-testimonial-count]");let testimonialIndex=0;const showTestimonial=index=>{testimonialIndex=(index+cards.length)%cards.length;track.style.transform=`translateX(-${testimonialIndex*100}%)`;sliderCount.textContent=`0${testimonialIndex+1} / 0${cards.length}`};testimonialSlider.querySelector("[data-testimonial-prev]").addEventListener("click",()=>showTestimonial(testimonialIndex-1));testimonialSlider.querySelector("[data-testimonial-next]").addEventListener("click",()=>showTestimonial(testimonialIndex+1));setInterval(()=>showTestimonial(testimonialIndex+1),6000)}
const consultationForm=document.querySelector("#consultation-form");
consultationForm?.addEventListener("submit",event=>{event.preventDefault();const name=document.querySelector("#name").value.trim();const phone=document.querySelector("#phone").value.trim();const email=document.querySelector("#email").value.trim();const reading=document.querySelector("#reading").value;const message=document.querySelector("#message").value.trim();const text=`Hello Riddhi Astrology,%0A%0AI would like to request a consultation.%0A%0AName: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0AEmail: ${encodeURIComponent(email||"Not provided")}%0AArea of guidance: ${encodeURIComponent(reading)}%0AMessage: ${encodeURIComponent(message||"Not provided")}`;window.open(`https://wa.me/919904025820?text=${text}`,"_blank","noopener")});
const carousel=document.querySelector("[data-carousel]");
if(carousel){const slides=[...carousel.querySelectorAll(".contact-slides img")];const carouselCount=carousel.querySelector("[data-count]");let carouselIndex=0;const showSlide=index=>{carouselIndex=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle("active",i===carouselIndex));carouselCount.textContent=`0${carouselIndex+1} / 0${slides.length}`};carousel.querySelector("[data-prev]").addEventListener("click",()=>showSlide(carouselIndex-1));carousel.querySelector("[data-next]").addEventListener("click",()=>showSlide(carouselIndex+1));setInterval(()=>showSlide(carouselIndex+1),4500)}
document.querySelectorAll(".faq-list:not(.accordion-faq)").forEach(list=>{[...list.children].forEach((item,index)=>{const heading=item.querySelector("h3");const answer=item.querySelector("p");if(!heading||!answer)return;item.classList.add("faq-item");if(index===0)item.classList.add("open");heading.replaceWith(Object.assign(document.createElement("button"),{className:"faq-question",type:"button",innerHTML:`<span>${heading.textContent}</span><b aria-hidden="true">+</b>`}));item.querySelector(".faq-question").setAttribute("aria-expanded",String(index===0));const answerWrap=document.createElement("div");answerWrap.className="faq-answer";answer.replaceWith(answerWrap);answerWrap.appendChild(answer)});list.classList.add("accordion-faq")});
document.querySelectorAll(".accordion-faq").forEach(list=>{const items=[...list.querySelectorAll(".faq-item")];items.forEach(item=>{const button=item.querySelector(".faq-question");button.addEventListener("click",()=>{const opening=!item.classList.contains("open");items.forEach(other=>{other.classList.remove("open");other.querySelector(".faq-question")?.setAttribute("aria-expanded","false")});if(opening){item.classList.add("open");button.setAttribute("aria-expanded","true")}})})});
const countElements=[...document.querySelectorAll("[data-count-to]")];
if(countElements.length){const countObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const element=entry.target;const target=Number(element.dataset.countTo);const suffix=element.dataset.countSuffix||"";const duration=1500;const start=performance.now();const formatter=new Intl.NumberFormat("en-IN");const animate=now=>{const progress=Math.min((now-start)/duration,1);const eased=1-Math.pow(1-progress,3);element.textContent=`${formatter.format(Math.round(target*eased))}${suffix}`;if(progress<1)requestAnimationFrame(animate)};requestAnimationFrame(animate);countObserver.unobserve(element)}),{threshold:.45});countElements.forEach(element=>countObserver.observe(element))}
